version: "{branch}-ci-{build}"
clone_depth: 5

install:
  - mkdir deps
  - mkdir deps\include
  - mkdir deps\lib
  - nuget install AllegroDeps -Version 1.3.0.2 -OutputDirectory deps -ExcludeVersion
  - ps: move deps\AllegroDeps\build\native\include\* deps\include -force
  - ps: move deps\AllegroDeps\build\native\lib\win32\v140\mt\* deps\lib -force

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015" -DWANT_ACODEC_DYNAMIC_LOAD=off -DFLAC_STATIC=on
  - cmake --build . --config RelWithDebInfo
